name: durian
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  lottie: ^2.6.0
  get: ^4.6.5
  flex_color_scheme: ^7.3.1
  fl_chart: ^0.63.0
  flutter_pdfview: ^1.3.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/bg/
    - assets/pdf/


